pipeline {
    agent any  // Pode rodar em qualquer agente

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/talytam/testes-api-cy.git'  
            }
        }
        stage('Instalar Dependências') {
            steps {
                sh 'npm install'
            }
        }
        stage('Iniciar Servidor') {
            steps {
                sh 'npm start & sleep 5'  
            }
        }
        stage('Rodar Testes') {
            steps {
                sh 'npm run cy:run'  
            }
        }
        stage('Gerar Relatório') {
            steps {
                sh 'npm run cy:report'  
            }
        }
        stage('Publicar Relatório') {
            steps {
                publishHTML(target: [
                    reportDir: 'mochawesome-report',
                    reportFiles: 'report.html',
                    reportName: 'Mochawesome Test Report'
                ])
            }
        }
    }
}